### ISSUE TITLE
После поиска ничего не происходит

### ISSUE THREAD

**Issue by disovi** [nyamzmeya/friends-vk#1]
https://nyamzmeya.github.io/friends-vk/#/

![image](https://user-images.githubusercontent.com/705617/170017496-7a4be62f-f9e7-4ce7-9bd1-414ac7c43ceb.png)

**Comment by nyamzmeya** [comment]
![image](https://user-images.githubusercontent.com/66028349/170130026-b4dd1077-11c3-4c07-9669-8d4a6826ac84.png)
Исправлено

**Comment by disovi** [comment]
@nyamzmeya всё ещё ошибка

![image](https://user-images.githubusercontent.com/705617/170292498-67e2a6c6-66cf-4470-89e3-fee1feb2c7a5.png)

**Comment by nyamzmeya** [comment]
@disovi была проблема с ключом доступа, сейчас должно работать
